ergo {
  nodeName = "EAGL-Node1"
  bindAddress = "0.0.0.0:9030"

  network {
    chainId = "EAGL"
    magicBytes = [0xE1, 0xA9, 0x6C, 0x01]
    bootstrapPeers = []
    knownPeers = []
  }

  blockchain {
    genesisHeight = 0
    initialDifficulty = 1
    blockInterval = 120s
    genesisTimestamp = 0
  }
}
